name: "Rest Assured CI"

on:
  schedule:
    - cron: "0 12 * * 5"
  push:
    branches: '**'
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-22.04

    env:
      API_KEY: ${{ secrets.API_KEY }}
      TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Run tests
        run: ./gradlew test

      - name: Generate allure report
        if: always()
        run: ./gradlew allureReport

      - name: Publish allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: build/allure-results
          retention-days: 5